[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[functions]
  external_node_modules = ["@prisma/client", "chrome-aws-lambda", "puppeteer-core"]
  included_files = ["prisma/**", "node_modules/chrome-aws-lambda/**"]
  node_bundler = "esbuild"

[functions.api]
  memory = 3008
  timeout = 30

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true