[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[functions]
  external_node_modules = ["@prisma/client", "@sparticuz/chromium"]
  included_files = ["prisma/**"]
  node_bundler = "esbuild"

[functions.api]
  memory = 3008
  timeout = 60

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true