[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  PRISMA_CLIENT_ENGINE_TYPE = "dataproxy"
  NODE_VERSION = "18"

[functions]
  external_node_modules = ["@prisma/client", "@prisma/extension-accelerate"]
  included_files = ["prisma/**"]
  node_bundler = "esbuild"

[functions.api]
  memory = 3008
  timeout = 60

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true